202402 functional navbar and final edits
mwbassette/Projects pull request #77
Opened 2024-03-20 04:43 UTC by mwbassette

2024-03-20 18:20 UTC, jjnotjayjay requested changes
Moving in the right direction on this one!  Keep up the great work!

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.html
> +                            <a href="/app/">DOWNLOAD</a>
🚀

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.html
> +                                <a href="/foragencies#contactus/">Contact Sales</a>
Ahh, watch out for this actually.  `/foragencies` is the path.  `#contactus` is the hash, which always comes after the path and can be used to link users directly to a specific part of a page.  

However, if you put a slash after the hash, the browser will interpret the path to be `foragencies#contactus` which will likely result in a 404 error.

I'd update this to `/foragencies/#contactus`.

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.html
> +                                <a href="/app?redir=appleapp/">
See the above note re: the `#contactus` hash.  Similar case here.  `?redir=appleapp` is the query string, which always comes after the hash, and which is used to pass information to a webpage.  (`/url-path/#hash?queryString=after`).  You'll want to put that ending slash after the path, as opposed to after the query string.

Query strings are pretty common, especially for things like search engines.  Head over to google and search for something, you'll see your search string in the URL in the browser after you search!

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.html
> +                                <a href="/app?redir=googleplay/">
See above note.

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +  if (!navbar) return;
🚀

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
What are lines 500-503 meant to accomplish?

2024-03-20 18:20 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button.inactive-background {
What triggers `inactive-background`?  Is this handling necessary, and if so, for what?

2024-03-21 02:46 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button.inactive-background {
Nothing and no. It is a remnant of a previous idea, and now it doesn't exist. :]

2024-03-21 02:54 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
Well, the problem I seemed to be running into was the :hover properties were remaining after clicking on the button, even when my mouse wasn't hovering over it. After tinkering with the properties, I found that by switching to the :active pseudo-class, I could mitigate that unwanted effect.

2024-03-21 02:55 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/index.html
> +                                <a href="/app?redir=appleapp/">
Interesting! I learned about hashes and query strings today.

2024-03-21 02:55 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/index.html
> +                                <a href="/foragencies#contactus/">Contact Sales</a>
Committed

2024-03-21 02:55 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/index.html
> +                                <a href="/app?redir=googleplay/">
Committed

2024-03-21 02:56 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
But now the :hover effect is gone... :(

2024-03-21 02:57 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
Assuming you'd still want to keep the :hover effect, I'll figure out a way to keep both effects.

2024-03-21 05:03 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
It seems that the problem only occurs when using the dev tools inspect feature. Without it, it runs as expected. Any thoughts?

2024-03-21 07:09 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
Let me ask it a slightly different way - what is the _goal_ of this handling?  i.e. what is supposed to change on the website as a result of this code, and when is that change supposed to incur?

Once you've answered those questions (only after you're done answering those questions), then look up what triggers the `:hover` and `:active` states (and `:focus` while you're at it), and how they're different.  Good things to know.

Then, ask yourself if there are any other solutions that accomplish the goal (as outlined in the first paragraph above) without any unintended side effects, and go from there.

2024-03-21 07:10 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/styles.css
> +    .mobile-nav-button:active {
No worries if you're unable to figure it out, but spend some time trying to figure it out (10-no more than 30 mins depending on your mood) and I can address this tmrw 👍

2024-03-21 07:17 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +  } else if (mobileWindowSize) {
Can you outline a situation where this `else if` statement is required?  Any shorter/simpler way to accomplish this?

2024-03-21 07:17 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +mobileNav.addEventListener('click', changeMobileButtonBackgroundColor)
This is great!  It might make sense to put `changeMobileButtonBackgroundColor` and `displayMobileNavbarLinks` into one function, perhaps something like `showMobileNav`.  That way, you only need to add one `click` event listener, and any future additional functions that need to run whenever the mobile nav is toggled can be added without needing to add an additional click event.

2024-03-21 07:17 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +  if (!links) return
This is a bit of a trick question, and to answer correctly requires a bit of a high level of understanding of some stuff, but I'll ask it anyways because the answer might surprise you, and the investigation alone will teach you some stuff.

Will the `return` statement on line 29 ever run?  If yes, provide an example of when it will be triggered.  If no, say why.

2024-03-22 02:22 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +  } else if (mobileWindowSize) {
Fix as discussed :)

2024-03-22 02:27 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +mobileNav.addEventListener('click', changeMobileButtonBackgroundColor)
![Screenshot 2024-03-21 at 19 27 18](https://github.com/mwbassette/Projects/assets/39274776/7cbb7d8c-0017-42cc-966e-98012486bef9)

2024-03-22 02:27 UTC, jjnotjayjay commented on #6: Site Duplication - TokenTransit/index.js
> +mobileNav.addEventListener('click', changeMobileButtonBackgroundColor)
Look into something like this!

2024-03-22 05:15 UTC, mwbassette commented on #6: Site Duplication - TokenTransit/index.js
> +  if (!links) return
No, because even an empty nodelist object is still truthy.

2024-03-22 05:15 UTC, merged